apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monitoring
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
  namespace: monitoring
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: service-prometheus
          servicePort: 9090
