apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: fibservice-servicemonitor
  name: fibservice-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    port: web
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      tier: frontend